name: CI for backend
on:
  push:
    branches:
      - main
    paths:
      - "woldwolf-backend/**"
      - "!**.md"
  pull_request:
    branches:
      - "*"
    paths:
      - "woldwolf-backend/**"
      - "!**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
